dist: trusty
sudo: false
language: scala
scala:
  - 2.10.7
  - 2.11.12

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_script:
  - bash .setup_hdfs.sh

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
